services:
  node1:
    command: --datadir  /root/data --nodiscover --syncmode full --nodekey /root/files/priv.key
      --port 30313 --http --http.addr "0.0.0.0" --http.vhosts="*" --http.corsdomain="*"
      --http.port 8503 --http.api db,eth,net,web3,admin,personal,miner,signer:insecure_unlock_protect  --networkid
      1122 --unlock 0 --password /root/files/password --mine --allow-insecure-unlock  --ws
      --ws.port 33445 --ws.api eth,net,web3
    hostname: node_1
    image: ethereum/client-go
    ports:
    - 30313:30313
    - 8503:8503
    volumes:
    - ./nodes/node_1/keys/password:/root/files/password:ro
    - ./nodes/node_1/keys/priv.key:/root/files/priv.key:ro
    - ./nodes/node_1/data:/root/data:rw
    - /root/data/geth/nodes/
    - /root/data/geth/triecache/
version: '3'
